### ISSUE TITLE
Can't locate Parallel/ForkManager.pm in @INC

### ISSUE THREAD

**Issue by Shiva-brahmam03** [xuechantian/LncRNA-pipline#2]
I am struck here and unable to find the right package for the parallel::Forkmanager, even after installing multiple times it is not resolving. Is there any any link to get the package. 
Thank you.

**Comment by xuechantian** [comment]
Hello, have you finished the installation now? You can send me the code and error information of this step.
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jun 13, 2024 05:54 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[xuechantian/Plant-LncRNA-pipline] Can't locate Parallel/ForkManager.pm in @INC (Issue #2)

&nbsp;



 
I am struck here and unable to find the right package for the parallel::Forkmanager, even after installing multiple times it is not resolving. Is there any any link to get the package.
 Thank you.
